apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swagger-ui.fullname" . }}
  labels:
    {{- include "swagger-ui.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "api-specs/**.yaml").AsConfig | nindent 2 }}